// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type Product struct {
	ID        string `json:"_id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Price     int32  `json:"price"`
	Stock     int32  `json:"stock"`
}

type Query struct {
}

type User struct {
	ID       string `json:"_id"`
	UserID   string `json:"user_id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
